#!/usr/bin/perl

sub usage() {
    print <<EOD;

Extracts text and layout information from PDF documents, using
pdftohtml or cuneiform.

usage: $0 [-d int] [-p int] file.pdf

 -d int : debug level
 -p int : max. number of pages to parse

EOD
   exit;
}

use strict;
use warnings;
use Encode;
use FindBin qw($Bin);
use lib $Bin;
use util::Sysexec;
binmode STDOUT, ":utf8";

use constant PDFTOHTML    => '/usr/bin/pdftohtml';
use constant TEMPDIR 	  => $Bin.'/temp';

my %opt = ( "d" => 0 );
my $pdf;
sub init() {
    use Getopt::Std;
    getopts( "hvd:p:", \%opt ) or usage();
    usage() if $opt{h};
    @ARGV >= 1 || usage();
    $pdf = $ARGV[0] ;
}

sub pdf2xml {
    my $source = shift;
    die "$source does not exist" unless (-e $source);
    my $command = PDFTOHTML
        .' -i'            # ignore images
        .' -xml'          # xml output
        .' -enc \'UTF-8\''
        .' -stdout'       # output to stdout
        .' '.$source      # source file
        .' 2>&1';         # stderr to stdout
    my $xml = sysexec($command, 10, $opt{'d'}) || '';
    # strip anchors (inserted by pdftohtml for footnotes):
    $xml =~ s/<a[^>]+>(.+?)<\/a>/$1/gi;
    if ($xml && $xml =~ /<text.+?>.*\w{5}.*</) {
        # sometimes $text isn't really UTF8 and decode_utf8() returns undef
        $xml = Encode::decode_utf8($xml) || $xml;
        return $xml;
    }
    # if pdftohtml failed, we use OCR:
    print "pdftohtml failed on parsing. Using OCR.\n" if $opt{'d'};
    $xml = '';
    my $tmp = TEMPDIR;
    $command = "./pdfocr -w $tmp $source $tmp/out.hocr"
        ." && ./hocr2xml $tmp/out.hocr $tmp/out.xml";
    sysexec($command, 30, $opt{'d'});
    open INPUT, "$tmp/out.xml" or die "OCR failed.";
    while (<INPUT>) { $xml .= $_; }
    close INPUT;
    if (!$xml || $xml !~ /\w{5}.*<\/text/) {
        die "OCR failed. $xml $!";
    }
    `rm $tmp/out.*`;
    # fix some common OCR mistakes:
    $xml =~ s/(?<=[a-z])0(?=[a-z])/o/g;    # 0 => o
    $xml =~ s/(?<=[a-z])1(?=[a-z])/i/g;    # 1 => i
    $xml =~ s/. .u \&\#174\;//g;           # This the JSTOR logo
    return $xml;
}

init();
my $out = pdf2xml($pdf);
print $out;

1;
