// Generated by generate_version_cc.sh
const char *hardcoded_version_string() {return "(revision n/a); Mon Apr 12 16:56:04 CEST 2010; Linux x61 2.6.31-20-generic #58-Ubuntu SMP Fri Mar 12 05:23:09 UTC 2010 i686 GNU/Linux";}
